### ISSUE TITLE
Since 33 Goto Definition Does Not Work On Linux 

### ISSUE THREAD

**Issue by maj-o** [visualfc/liteide#937]
Please answer these questions before submitting your issue. Thanks!
Please download LiteIDE latest version and test before submitting your issue. Thanks!

### What version of LiteIDE are you using (LiteIDE About - Version and Build Qt Version)?

Does not work:
liteide-33.2-2-x86_64
liteide-33.2-1-x86_64
liteide-33.1-1-x86_64
liteide-33-3-x86_64
liteide-33-2-x86_64
liteide-33-1-x86_64

Works:
liteide-32-2-x86_64

### What version of Go are you using (`go version`)?

go version go1.10.2 linux/amd64

### What operating system and processor architecture are you using(`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/andreas/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/andreas/Projects/go"
GORACE=""
GOROOT="/usr/lib/go"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build460373721=/tmp/go-build -gno-record-gcc-switches"

### What did you do?

Open source code open context menu for a string, select "Goto Definition"

### What did you expect to see?

The source of the definition.

### What did you see instead?

08:00:47 find def error: Prozess beendet mit Rückgabewert 1

(German for "process ended returning 1")

**Comment by vedranvuk** [comment]
Set a fixed GOROOT and GOPATH in an environment file as a temporary fix.

**Comment by visualfc** [comment]
archlinux please download from https://github.com/visualfc/liteide/releases pkgbuild
https://github.com/visualfc/liteide/releases/download/x33.3/liteidex33.3.archlinux-pkgbuild.zip

**Comment by maj-o** [comment]
@vedranvuk : can You please give an example, cause i don't know what You meen.

**Comment by maj-o** [comment]
@visualfc : 33.3 does not work.

**Comment by abhishekbarua** [comment]
I confirm the problem is happening in Manjaro Linux also. My go environment is similar.

**Comment by maj-o** [comment]
News: 33.3 from official package (arch) does not work. But the liteide-git package works. Maybe the problem has been solved as commented by visualfc.

**Comment by abhishekbarua** [comment]
Is this related to the autocompletion problem also?

**Comment by vedranvuk** [comment]
It does affect autocompletion as gocode environment is set by liteide.

There might also be a related bug where when changing the active file in the editor does not always set the related environment, and this mainly happens with test files.

**Comment by visualfc** [comment]
please download x35.1 and check.

**Comment by vendelin8** [comment]
This still doesn't work for me on x35.5-1, Arch Linux, linux_amd64.

I usually replace `/usr/bin/gocode` with one from `github.com/mdempsky/gocode`, because the original works only for local names. The original gocode doesn't do anything with names outside the package, even standard packages like os or path. Having that, I get `find def error: process exited with code 2` for finding definition.

When I reinstall the package to get back original gocode, finding the definition fails silently.
